### PR TITLE
fix: improve regex path matching

### LINKED ISSUE #87: Destiny only treat import paths that start with a dot
[Our regex](https://github.com/benawad/destiny/blob/001ea49279314b7d41ff4e189eff1c00e4062d87/src/index/shared/findImports.ts#L5) only match with import paths that start with a dot.

That's an issue because destiny is trying to resolve this import's package name as a path:
```js
import '..something';
// or
import '.something';
```

Also I don't think npm is allowing dots in packages name. But destiny should probably ignore this kind of import anyway...

See:
https://regexr.com/4vc8q

### PR DESCRIPTION
**Pull request by sQVe**
See https://regex101.com/r/SkaHYp/1/ for further details.

This closes #87.

### CODE REVIEW

File: src/index/shared/findImports.ts [hunk 1]
```diff
@@ -2,21 +2,20 @@ import fs from "fs";
...
-  while ((matches = importRegex.exec(fileContent)) !== null) {
+  while ((matches = reImport.exec(fileContent)) !== null) {
     // This is necessary to avoid infinite loops with zero-width matches.
-    if (matches.index === importRegex.lastIndex) {
-      importRegex.lastIndex++;
+    if (matches.index === reImport.lastIndex) {
+      reImport.lastIndex++;
     }
-    importPaths.push(matches[1] ?? matches[2]);
+    importPaths.push(matches[1]);
```
Comment (waynevanson) [inline src/index/shared/findImports.ts]: Slick!
